{% set name = "sequdas_qc" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

# source:
#   url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
#   sha256: "6df4205c38b750eb4c296fda978ff5913d91a2fe655583b2bb109ce63d0be7d0"

source:
  url: "https://test-files.pythonhosted.org/packages/a7/47/f32c93cd083ee087a99957ffc862ed1a3eda479880490ea06dd390a01bd1/sequdas_qc-1.0.0.3.tar.gz"
  sha256: "dd2457dac4e4fa314a97ee4a21db5a0b226e0266d593b234abefb5c7c2cbcfd8"

build:
  number: 0
  entry_points:
    - sequdas_qc=sequdas_qc.sequdas_qc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

channels:
  - defaults
  - bioconda
  - conda-forge

requirements:
  host:
    - python>=3.6
  run:
    - python>=3.6
    - configparser
    - pymysql
    - pytz
    - ntplib
    - validate_email
    - paramiko
    - kraken2
    - krona
    - illumina-interop
    - samtools
    - fastqc
    - hashdeep

test:
  imports:
    - sequdas_qc

about:
  home: "https://github.com/duanjunhyq/sequdas"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "SeqUDAS: Sequence Upload and Data Archiving System"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - duanjunhyq
